services:
  ginger_db:
    image: postgres:16
    container_name: ginger_db
    environment:
      POSTGRES_DB: ginger
      POSTGRES_USER: ginger_user
      POSTGRES_PASSWORD: ginger_pass
    ports:
      - "5432:5432"
    volumes:
      - ginger_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ginger_user -d ginger"]
      interval: 5s
      timeout: 3s
      retries: 20

  ginger_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ginger_backend
    depends_on:
      ginger_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ginger_db:5432/ginger
      SPRING_DATASOURCE_USERNAME: ginger_user
      SPRING_DATASOURCE_PASSWORD: ginger_pass

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      GEMINI_API_KEY: ${GEMINI_API_KEY}
      APP_AI_MODEL: ${APP_AI_MODEL:-gemini-3-flash-preview}

      # Ajusta si tu app escucha en otro puerto
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped

  ginger_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: http://localhost:8081/api
    container_name: ginger_frontend
    depends_on:
      - ginger_backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  ginger_pgdata:
